backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "produto" # Used in routes, e.g., /admin/collections/blog
    label: "Produto" # Used in the UI
    folder: "_docs/produto" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "string" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Preço", name: "price", widget: "number", valueType: "float" }
      - { label: "Ordem", name: "order", widget: "number" }
  - name: "configs" # Used in routes, e.g., /admin/collections/blog
    label: "Configurações" # Used in the UI
    files:
      - file: "_docs/configs/seo.md"
        label: "SEO"
        name: "seo"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "string" }
          - { label: "Imagem", name: "image", widget: "image" }
          - { label: "Palavras-Chave", name: "keywords", widget: "list" }
      - file: "_docs/paginas/home.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Título da aba", name: "pageTitle", widget: "string" }
          - { label: "Título da página", name: "title", widget: "string" }
      - file: "_docs/paginas/carrinho.md"
        label: "Carrinho"
        name: "cart"
        fields:
          - { label: "Cabeçalho", name: "title", widget: "string" }
          - { label: "Carrinho vazio - título", name: "emptyMsgTitle", widget: "string" }
          - { label: "Carrinho vazio - subtítulo", name: "emptyMsgSubtitle", widget: "string" }
          - { label: "Frete", name: "freteMsg", widget: "string" }
          - { label: "Passo 1", name: "step1", widget: "string" }
          - { label: "Passo 2", name: "step2", widget: "string" }
          - { label: "Botão Pedir", name: "pedirBtn", widget: "string" }
          - { label: "Botão Limpar", name: "limparBtn", widget: "string" }
      - file: "_docs/paginas/rodape.md"
        label: "Rodapé"
        name: "footer"
        fields:
          - { label: "Sobre - Título", name: "aboutUsTitle", widget: "string" }
          - { label: "Sobre - Conteúdo", name: "aboutUsMsg", widget: "string" }
          - { label: "Horários - Título", name: "businessHoursTitle", widget: "string" }
          - { label: "Horários - Conteúdo", name: "businessHoursMsg", widget: "string" }
          - { label: "Contato - Título", name: "contactTitle", widget: "string" }
          - { label: "Contato - Conteúdo", name: "contactMsg", widget: "string" }
